### ISSUE TITLE
Chrome compatibility issue

### ISSUE THREAD

**Issue by jmecn** [henrikingo/impress.js#10]
I use impress.js + markdown.js on Chrome (v46.0.2490.86) these days, there are some compatibility problems.

* function default arguments

First error chrome give me is this:

![image](https://cloud.githubusercontent.com/assets/5283598/21465798/bd5131e4-c9ec-11e6-8389-429778514050.png)

I see this in impress.js:470

        var goto = function ( el, duration, reason = "goto") {

the argument `reason` was used in line 494

                event.detail.reason = reason;

I don't known why chrome don't support this syntax, but I changed it a little.

        var goto = function ( el, duration, reason) {

                event.detail.reason = reason || "goto";

* for of loop

After I solved first error, then comes this one:

![image](https://cloud.githubusercontent.com/assets/5283598/21465836/05f49e08-c9ee-11e6-87ad-ecbe28925eef.png)

line:1097

            for (var element of markdownDivs) {

Changed it to:

            for(var idx=0; idx<markdownDivs.length; idx++) {
            	var element = markdownDivs[idx];

Now it works for me.

**Comment by henrikingo** [comment]
Interesting. I do test on Google Chrome and this works for me. Out of curiosity, what version do you have? My Chrome is: 55.0.2883.75 (64-bit, Linux)

I do like your proposed changes though, so I will apply them. Thanks for sharing the fix!

**Comment by jmecn** [comment]
It's Ver 46.0.2490.86 (64, Windows). I work on win7 64-bit.

**Comment by henrikingo** [comment]
Ah, that's the reason then. At least for the second one I was aware it was modern JS syntax, but assumed by 2016 it was safe to use it. I'm glad you provided these fixes though, because it turns out the node build.js script that can be used to create a minified impress.min.js file had been broken for a while (at least for my installation of node), because I had introduced this new syntax. The compiler just fails without telling which line to fix, so I had put off searching for a solution. But with your fixes the compilation of a minified file works again!

**Comment by jmecn** [comment]
Glad to be of some help. ; )
