### ISSUE TITLE
Substeps?

### ISSUE THREAD

**Issue by KeineLimonade** [henrikingo/impress.js#12]
You did a great job of implementing plugins into impress.js, so i´d like to suggest to add this plugin for substeps: 
https://github.com/rethna2/microsteps

**Comment by henrikingo** [comment]
Thanks @Julisep 

I'm aware of the corresponding discussion in upstream impress.js. In fact, I think now this is the last feature request I'd like to add but haven't yet. (The past months I've been more focused on https://github.com/henrikingo/impressionist)

One reason I kept postponing addition of substeps was to reflect over both the desired user interfacing side of it and how to implement it as a plugin. I've come to the conclusion I want to extend the current plugin api, so that a substep plugin can cancel the transition to a new step, for example by returning false.

So for now all that remains is to actually implement that. Thanks for filing the ticket here, I think it is appropriate as I do want to include this.

**Comment by KeineLimonade** [comment]
I already implemented a little hack to solve this issue for me.

So I close this issue.

**Comment by henrikingo** [comment]
Ok. FWIW, my idea to implement substeps via a plugin would be similar to the stop plugin, which prevents the presentation from moving to the next step, and then of course need to add code to actually do the substep functionality.
