### ISSUE TITLE
https://github.com/impress/impress.js/issues/611

### ISSUE THREAD

**Issue by naraesk** [henrikingo/impress.js#13]
I just created a nex pull requested at the original impress.js repository: https://github.com/impress/impress.js/issues/611

Then I discovered your fork and was wondering if your navigation plugin is already capable of the described functionality? Further, is this supposed to be a permanent fork or what are your plans?

**Comment by henrikingo** [comment]
> I  just created a nex pull requested at the original impress.js repository: impress#611

May not be relevant, but just for clarity: I see an issue but no pull request (no code)

> Then  I discovered your fork and was wondering if your navigation plugin is already capable of the described functionality? 

It is not, however I've discussed this somewhere before (don't remember where), and the answer is that it would be straightforward to implement and I do like the idea.

Basically, in this fork you'll find [navigation plugin](https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/navigation) and [goto plugin](https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/goto). The goto plugin allows you to jump to some other slide than the next slide, by setting an attribute on the step element.

    <div class="step" data-goto="step-5">

To do what you're suggesting, one would have to combine information from the navigation plugin, so that you could go to different next slides, depending on which key was pressed. For example:

    <div class="step" data-goto-up="step-5" data-goto-right="step-15">

> Further, is this supposed to be a permanent fork or what are your plans?

As you can see, currently this fork is rather far ahead of the upstream repo. I have however taken great care to remain compatible with upstream and periodically merge from there. Also, the plugin framework I developed is based on the vision of @bartaz, so I believe it is in line with the vision he had when he created impress.js years ago.

My intent has always been to contribute this work back upstream, and I started it with helpful collaboration from @bartaz. But unfortunately the upstream repo has basically seen no development in years. (There was some documentation and testing added last year, but my fork is the only place where you'll see actual code changes.)

I continue to hope this code can be merged upstream at some point and would support that if there would be some signs of activity upstream. Otoh, github makes forking a dead project easy, and users are starting to find this, so I don't think the current situation is that bad either.

**Comment by naraesk** [comment]
Thanks for your quick response and explenation. I meant issue, of course.

`<div class="step" data-goto-up="step-5" data-goto-right="step-15">`

Sounds good!

> My intent has always been to contribute this work back upstream, and I started it with helpful collaboration from @bartaz. But unfortunately the upstream repo has basically seen no development in years. 

I'm using https://github.com/regebro/hovercraft/ to create impress.js presentations, so it's not this simple to switch to your implementation. Might be a good idea to convince it's maintainer to support it.

**Comment by henrikingo** [comment]
I once used hovercraft as well. Some features I've added from that:

* Relative positioning plugin (rel)
* impressConsole presenter console
* The help box that you see in bottom right
* Eventually I have also added Markdown support, which is similar to the RST support in hovercraft

The one major missing feature is the ability to position slides along a SVG path. That could be added as another positioning plugin, of course. But it's rather complicated and I never needed it or saw anyone who asked for it.

**Comment by naraesk** [comment]
Main advantage of hovercraft is the easier syntax, from my point of view. However, if you would implement this request, I would try again writing the html code myself. ;-)

**Comment by henrikingo** [comment]
I agree. I've tried to address that with adding [support for Markdown.js](http://henrikingo.github.io/impress.js/examples/markdown/#/markdown). But of course the approach is different: You write the Markdown inside a html file (template), not a clean Markdown file where HTML is added later and you don't need to see it.

**Comment by henrikingo** [comment]
Hi @naraesk 

I implemented something that allows "2D navigation" now (in fact, arbitrary navigation).

README: https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/goto/README.md
Demo: http://henrikingo.github.io/impress.js/examples/cube/#/step-1 (use arrow keys)

Let me know if this works for you.

**Comment by henrikingo** [comment]
Sorry, didn't intend to close before you comment :-)
